FROM ubuntu:20.04

WORKDIR /workspace/storage

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    nodejs \
    git \
    sqlite3
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    npm
RUN rm -rf /var/lib/apt/lists/*

COPY server.js server.js
COPY package-lock.json package-lock.json
COPY package.json package.json

RUN npm install

ENTRYPOINT ["node", "./server.js"]
